openapi: 3.0.0
info:
  title: openweathermap
  version: '1.0'
  contact:
    name: Support
    url: 'https://openweathermap.org/api'
    email: some_email@gmail.com
  termsOfService: 'Terms of service URL: https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
paths:
  /weather:
    get:
      summary: weather
      tags:
        - Weather endpoints
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  coord:
                    type:
                      - string
                      - object
                    properties:
                      lon:
                        type: number
                        example: 0
                      lat:
                        type: number
                  name:
                    type: string
                  id:
                    type: number
                  timezone:
                    type: number
                    description: The timezone for the station
              examples:
                example-1:
                  value:
                    coord:
                      lon: 124.52
                      lat: 84.63
                    name: string
                    id: 0
                    timezone: 0
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauth_response'
      operationId: get-weather
      description: get weather
      security:
        - app_id: []
      parameters:
        - schema:
            type: string
          in: query
          name: zip
          description: '**Zip code**: Search by zip code. *Example: 98101'
        - schema:
            type: string
          in: query
          name: id
          description: |
            **City ID**: *Example: 234562
    parameters: []
components:
  schemas:
    unauth_response:
      title: 401
      type: object
      properties:
        id:
          type: string
        message:
          type: string
        cod:
          type: integer
      required:
        - id
        - message
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
tags:
  - name: Weather endpoints
